export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const USER_LOGGEDIN = "USER_LOGGEDIN";